STATUS_OPTIONS = [
    {"label": "规划中", "value": "planning"},
    {"label": "进行中", "value": "active"},
    {"label": "已挂起", "value": "paused"},
    {"label": "已关闭", "value": "closed"},
    {"label": "草稿", "value": "draft"},
    {"label": "待办", "value": "todo"},
    {"label": "修复中", "value": "fixing"},
    {"label": "待验证", "value": "verifying"},
]


def object_options() -> list[dict[str, str]]:
    return [
        {"label": "项目", "value": "project"},
        {"label": "项目集", "value": "program"},
        {"label": "迭代", "value": "iteration"},
        {"label": "需求", "value": "requirement"},
        {"label": "任务", "value": "task"},
        {"label": "Bug", "value": "bug"},
        {"label": "测试用例", "value": "test_case"},
    ]


WORKFLOW_HANDLERS = [
    {
        "handler_key": "status_changed",
        "handler_type": "trigger",
        "label": "状态变更",
        "description": "对象状态从一个值流转到另一个值时触发。",
    },
    {
        "handler_key": "execution_result_changed",
        "handler_type": "trigger",
        "label": "执行结果变更",
        "description": "测试用例等执行结果变化时触发。",
    },
    {
        "handler_key": "field_changed",
        "handler_type": "trigger",
        "label": "字段变更",
        "description": "对象字段值发生变化时触发。",
    },
    {
        "handler_key": "status_matches",
        "handler_type": "condition",
        "label": "状态匹配",
        "description": "判断当前对象状态是否在指定范围。",
    },
    {
        "handler_key": "child_unclosed_exists",
        "handler_type": "condition",
        "label": "存在未关闭子对象",
        "description": "判断当前对象下是否存在未关闭的子对象。",
    },
    {
        "handler_key": "field_required",
        "handler_type": "condition",
        "label": "字段必填",
        "description": "判断上下文中的指定字段是否有值。",
    },
    {
        "handler_key": "role_matches",
        "handler_type": "condition",
        "label": "角色匹配",
        "description": "判断当前用户是否具有指定角色。",
    },
    {
        "handler_key": "change_current_status",
        "handler_type": "action",
        "label": "修改当前对象状态",
        "description": "将当前对象状态修改为指定状态。",
    },
    {
        "handler_key": "batch_change_child_status",
        "handler_type": "action",
        "label": "批量修改子对象状态",
        "description": "批量修改当前对象下的子对象状态。",
    },
    {
        "handler_key": "assign_owner",
        "handler_type": "action",
        "label": "设置负责人",
        "description": "按规则设置负责人。",
    },
    {
        "handler_key": "create_bug",
        "handler_type": "action",
        "label": "创建 Bug",
        "description": "根据上下文创建 Bug。",
    },
    {
        "handler_key": "send_notification",
        "handler_type": "action",
        "label": "发送通知",
        "description": "向指定接收人发送通知。",
    },
    {
        "handler_key": "block_operation",
        "handler_type": "action",
        "label": "阻断操作",
        "description": "阻断当前业务操作并返回提示。",
    },
    {
        "handler_key": "write_history",
        "handler_type": "action",
        "label": "写入操作历史",
        "description": "写入状态或工作流执行历史。",
    },
]


def handler_keys() -> set[str]:
    return {handler["handler_key"] for handler in WORKFLOW_HANDLERS}


DEFAULT_WORKFLOW_COMPONENTS = [
    {
        "component_key": "project_status_changed",
        "component_type": "trigger",
        "component_name": "项目状态变更",
        "description": "当项目从一个状态流转到另一个状态时触发。",
        "object_type": "project",
        "handler_key": "status_changed",
        "config_schema": [
            {"field": "from_status", "label": "来源状态", "type": "select", "options": STATUS_OPTIONS, "allow_any": True},
            {"field": "to_status", "label": "目标状态", "type": "select", "options": STATUS_OPTIONS},
        ],
        "enabled": True,
        "is_system": True,
        "sort_order": 10,
    },
    {
        "component_key": "program_status_changed",
        "component_type": "trigger",
        "component_name": "项目集状态变更",
        "description": "当项目集状态变化时触发。",
        "object_type": "program",
        "handler_key": "status_changed",
        "config_schema": [{"field": "to_status", "label": "目标状态", "type": "select", "options": STATUS_OPTIONS}],
        "enabled": True,
        "is_system": True,
        "sort_order": 20,
    },
    {
        "component_key": "iteration_status_changed",
        "component_type": "trigger",
        "component_name": "迭代状态变更",
        "description": "当迭代状态变化时触发。",
        "object_type": "iteration",
        "handler_key": "status_changed",
        "config_schema": [{"field": "to_status", "label": "目标状态", "type": "select", "options": STATUS_OPTIONS}],
        "enabled": True,
        "is_system": True,
        "sort_order": 30,
    },
    {
        "component_key": "requirement_status_changed",
        "component_type": "trigger",
        "component_name": "需求状态变更",
        "description": "当需求状态变化时触发。",
        "object_type": "requirement",
        "handler_key": "status_changed",
        "config_schema": [{"field": "to_status", "label": "目标状态", "type": "select", "options": STATUS_OPTIONS}],
        "enabled": True,
        "is_system": True,
        "sort_order": 40,
    },
    {
        "component_key": "task_status_changed",
        "component_type": "trigger",
        "component_name": "任务状态变更",
        "description": "当任务状态变化时触发。",
        "object_type": "task",
        "handler_key": "status_changed",
        "config_schema": [{"field": "to_status", "label": "目标状态", "type": "select", "options": STATUS_OPTIONS}],
        "enabled": True,
        "is_system": True,
        "sort_order": 50,
    },
    {
        "component_key": "bug_status_changed",
        "component_type": "trigger",
        "component_name": "Bug 状态变更",
        "description": "当 Bug 状态变化时触发。",
        "object_type": "bug",
        "handler_key": "status_changed",
        "config_schema": [{"field": "to_status", "label": "目标状态", "type": "select", "options": STATUS_OPTIONS}],
        "enabled": True,
        "is_system": True,
        "sort_order": 60,
    },
    {
        "component_key": "test_case_result_changed",
        "component_type": "trigger",
        "component_name": "用例执行结果",
        "description": "当测试用例执行结果为失败或阻塞时触发。",
        "object_type": "test_case",
        "handler_key": "execution_result_changed",
        "config_schema": [
            {
                "field": "result_in",
                "label": "执行结果",
                "type": "multi_select",
                "options": [{"label": "失败", "value": "failed"}, {"label": "阻塞", "value": "blocked"}],
            }
        ],
        "enabled": True,
        "is_system": True,
        "sort_order": 70,
    },
    {
        "component_key": "field_changed",
        "component_type": "trigger",
        "component_name": "字段变更",
        "description": "当负责人、状态等字段变化时触发。",
        "object_type": None,
        "handler_key": "field_changed",
        "config_schema": [{"field": "field_key", "label": "字段标识", "type": "text"}],
        "enabled": True,
        "is_system": True,
        "sort_order": 80,
    },
    {
        "component_key": "status_matches",
        "component_type": "condition",
        "component_name": "状态匹配",
        "description": "判断当前对象状态是否满足条件。",
        "object_type": None,
        "handler_key": "status_matches",
        "config_schema": [{"field": "status_in", "label": "状态范围", "type": "multi_select", "options": STATUS_OPTIONS}],
        "enabled": True,
        "is_system": True,
        "sort_order": 110,
    },
    {
        "component_key": "child_unclosed_exists",
        "component_type": "condition",
        "component_name": "存在未关闭子对象",
        "description": "判断项目、需求等对象下是否存在未关闭子对象。",
        "object_type": None,
        "handler_key": "child_unclosed_exists",
        "config_schema": [
            {"field": "child_object", "label": "子对象", "type": "select", "options": object_options()},
            {"field": "status_not_in", "label": "排除状态", "type": "multi_select", "options": STATUS_OPTIONS},
        ],
        "enabled": True,
        "is_system": True,
        "sort_order": 120,
    },
    {
        "component_key": "field_required",
        "component_type": "condition",
        "component_name": "字段必填",
        "description": "校验日期、原因、负责人等字段必填。",
        "object_type": None,
        "handler_key": "field_required",
        "config_schema": [{"field": "field_key", "label": "字段标识", "type": "text"}],
        "enabled": True,
        "is_system": True,
        "sort_order": 130,
    },
    {
        "component_key": "role_matches",
        "component_type": "condition",
        "component_name": "角色匹配",
        "description": "限制只有特定角色可以执行后续动作。",
        "object_type": None,
        "handler_key": "role_matches",
        "config_schema": [{"field": "role_key", "label": "角色标识", "type": "text"}],
        "enabled": True,
        "is_system": True,
        "sort_order": 140,
    },
    {
        "component_key": "change_current_status",
        "component_type": "action",
        "component_name": "修改当前对象状态",
        "description": "将当前对象状态修改为指定结果。",
        "object_type": None,
        "handler_key": "change_current_status",
        "config_schema": [{"field": "target_status", "label": "目标状态", "type": "select", "options": STATUS_OPTIONS}],
        "enabled": True,
        "is_system": True,
        "sort_order": 210,
    },
    {
        "component_key": "batch_change_child_status",
        "component_type": "action",
        "component_name": "批量修改子对象状态",
        "description": "批量修改子对象状态，例如关闭项目下未关闭需求。",
        "object_type": None,
        "handler_key": "batch_change_child_status",
        "config_schema": [
            {"field": "child_object", "label": "子对象", "type": "select", "options": object_options()},
            {"field": "target_status", "label": "目标状态", "type": "select", "options": STATUS_OPTIONS},
            {"field": "reason", "label": "原因", "type": "text"},
        ],
        "enabled": True,
        "is_system": True,
        "sort_order": 220,
    },
    {
        "component_key": "assign_owner",
        "component_type": "action",
        "component_name": "设置负责人",
        "description": "按项目负责人、需求负责人等规则设置负责人。",
        "object_type": None,
        "handler_key": "assign_owner",
        "config_schema": [{"field": "owner_source", "label": "负责人来源", "type": "text"}],
        "enabled": True,
        "is_system": True,
        "sort_order": 230,
    },
    {
        "component_key": "create_bug",
        "component_type": "action",
        "component_name": "创建 Bug",
        "description": "根据用例执行结果创建 Bug。",
        "object_type": "test_case",
        "handler_key": "create_bug",
        "config_schema": [{"field": "bug_type", "label": "Bug 类型", "type": "text"}],
        "enabled": True,
        "is_system": True,
        "sort_order": 240,
    },
    {
        "component_key": "send_notification",
        "component_type": "action",
        "component_name": "发送通知",
        "description": "通知负责人、测试人员或项目负责人。",
        "object_type": None,
        "handler_key": "send_notification",
        "config_schema": [{"field": "receiver", "label": "接收人", "type": "text"}],
        "enabled": True,
        "is_system": True,
        "sort_order": 250,
    },
    {
        "component_key": "block_operation",
        "component_type": "action",
        "component_name": "阻断操作",
        "description": "不满足规则时阻断当前操作并展示提示。",
        "object_type": None,
        "handler_key": "block_operation",
        "config_schema": [{"field": "message", "label": "提示语", "type": "textarea"}],
        "enabled": True,
        "is_system": True,
        "sort_order": 260,
    },
    {
        "component_key": "write_history",
        "component_type": "action",
        "component_name": "写入操作历史",
        "description": "记录状态变化、批量动作和执行备注。",
        "object_type": None,
        "handler_key": "write_history",
        "config_schema": [{"field": "remark", "label": "备注模板", "type": "textarea"}],
        "enabled": True,
        "is_system": True,
        "sort_order": 270,
    },
]
